name: Auto Start Bot on Push

# Start the workflow only when 'start.txt' is pushed to the main branch
on:
  push:
    branches:
      - main  # Adjust if you want a different branch
    paths:
      - 'start.txt'  # Trigger only when the 'start.txt' file is changed

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Automatically stop the bot after 1 hour

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        run: |
          python bot.py  # Replace `bot.py` with your bot's main file

      # Force cleanup after the run, including if the job is canceled
      - name: Force Cleanup Files and Cache
        if: always()  # Ensure this runs even if the job is canceled
        run: |
          rm -rf *                         # Remove all files and directories in the workspace
          rm -rf /tmp/*                    # Clear temp files if any
          find . -type f -size +500k -delete  # Extra safeguard: delete remaining files larger than 500KB
