name: Auto Start Bot on Push

on:
  push:
    branches:
      - main
    paths:
      - 'start.txt'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Increase timeout if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debugging Info
        run: |
          echo "Current Directory: $(pwd)"
          echo "Listing Files: $(ls -l)"
          echo "Secrets are set up properly."
      
      - name: Run the bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN: ${{ secrets.ADMIN }}
          CAPTION: ${{ secrets.CAPTION }}
        run: |
          python bot.py  # Replace `bot.py` with your bot's main file

      - name: Force Cleanup Files and Cache
        if: always()
        run: |
          rm -rf *                         
          rm -rf /tmp/*                    
          find . -type f -size +500k -delete
